### ISSUE TITLE
CascadingCodeTimer causes Access Denied on Azure AppService

### ISSUE THREAD

**Issue by rachael-ross** [json-api-dotnet/JsonApiDotNetCore#1159]
#### DESCRIPTION

JADNC throwing exception when hosted in Azure AppService. I've traced the source code line to line 26 of the **CascadingCodeTimer**, in which Azure AppService states **Access Denied** :

```
 static CascadingCodeTimer()
    {     
           ...
            // The most important thing is to prevent switching between CPU cores or processors. Switching dismisses the cache, etc. and has a huge performance impact on the test.
            Process.GetCurrentProcess().ProcessorAffinity = new IntPtr(2);
          ...     
    }
```

Recompiled without DEBUG symbol to set the session manager to NOT be enabled, but still getting the error. 

Ideas??

#### ACTUAL BEHAVIOR

```
System.TypeInitializationException: The type initializer for 'JsonApiDotNetCore.Diagnostics.CascadingCodeTimer' threw an exception.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.set_ProcessorAffinityCore(IntPtr value)
   at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value)
   at JsonApiDotNetCore.Diagnostics.CascadingCodeTimer..cctor() in C:\SourceCode\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\Diagnostics\CascadingCodeTimer.cs:line 26
   --- End of inner exception stack trace ---
   at JsonApiDotNetCore.Diagnostics.CascadingCodeTimer..ctor() in C:\SourceCode\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\Diagnostics\CascadingCodeTimer.cs:line 13
   at JsonApiDotNetCore.Diagnostics.AspNetCodeTimerSession.get_CodeTimer() in C:\SourceCode\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\Diagnostics\AspNetCodeTimerSession.cs:line 28
   at JsonApiDotNetCore.Diagnostics.CodeTimingSessionManager.get_Current() in C:\SourceCode\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\Diagnostics\CodeTimingSessionManager.cs:line 27
   at JsonApiDotNetCore.Middleware.JsonApiMiddleware.InvokeAsync(HttpContext httpContext, IControllerResourceMapping controllerResourceMapping, IJsonApiOptions options, IJsonApiRequest request, ILogger`1 logger) in C:\SourceCode\Repos\JsonApiDotNetCore\src\JsonApiDotNetCore\Middleware\JsonApiMiddleware.cs:line 46
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```
#### VERSIONS USED
- JsonApiDotNetCore version: 5.0.1
- ASP.NET Core version: 6
- Entity Framework Core version: 6
- Database provider: Sql Server

**Comment by rachael-ross** [comment]
Realized that I had a debug version of the nuget package pulled into my app. So pulling in a release build fixed it.

**Comment by bkoelman** [comment]
That makes sense. `CascadingCodeTimer` is not used in production (release builds). We only use it locally to measure the internal performance of the library.
