### ISSUE TITLE
AmbiguousActionException with 2.1.500 in RequestMiddleware

### ISSUE THREAD

**Issue by Dillie-O** [json-api-dotnet/JsonApiDotNetCore#460]
## Description

I recently scaffold up a fresh .Net Core 2.1.500 WebAPI project and then followed the basic installation directions on the site. I'm using the default "ValuesController" that comes with the project. After going through the required steps, I'm seeing the following error when I attempt to call my `Values` GetAll endpoint (as well as similar ones for `Values/5`) I get the following error

```
Microsoft.AspNetCore.Mvc.Internal.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

ivp_webapi.Controllers.ValuesController.GetAll (ivp-webapi)
ivp_webapi.Controllers.ValuesController.GetAsync (ivp-webapi)
   at Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestCandidate(RouteContext context, IReadOnlyList`1 candidates)
   at Microsoft.AspNetCore.Mvc.Internal.MvcAttributeRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.Tree.TreeRouter.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at JsonApiDotNetCore.Middleware.RequestMiddleware.Invoke(HttpContext context, IJsonApiContext jsonApiContext) in C:\projects\jsonapidotnetcore\src\JsonApiDotNetCore\Middleware\RequestMiddleware.cs:line 28
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I've tried a couple of things such as annotating the route differently but things don't seem to work. Is there a simple update I need to make? I notice that the sample code uses .Net 2.1.0 and I've even tried to restructure my controller/startup to use similar code to no avail.

Any idea on how to get the middleware to resolve properly (or ignore GetAsync?)

## Environment

- JsonApiDotNetCore Version: 3.0.0
- Other Relevant Package Versions: .Net Core 2.1.500

**Comment by jaredcnance** [comment]
Can you post the source for `ValuesController` ?

**Comment by Dillie-O** [comment]
Note: My `ValueCheck` is a pretty simple "dummy" object to get the basics working. 

```
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using JsonApiDotNetCore.Controllers;
using JsonApiDotNetCore.Services;
using ivp_webapi.Data;
using ivp_webapi.Models;

namespace ivp_webapi.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ValuesController : JsonApiController<ValueCheck>
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger _logger;
        private readonly IConfiguration _configuration;

        public ValuesController(
            IJsonApiContext jsonApiContext,
            IResourceService<ValueCheck> resourceService,
            ILoggerFactory loggerFactory) 
        : base(jsonApiContext, resourceService, loggerFactory)
        { }
        
        // GET /values
        [HttpGet]
        public ActionResult<IEnumerable<ValueCheck>> GetAll()
        {;
            return new ValueCheck[] 
            { 
                new ValueCheck { Name = "Value1", Value = 1}, 
                new ValueCheck { Name = "Value2", Value = 2},
                new ValueCheck { Name = "Value3", Value = 3} 
            };
        }

        // GET /values/5
        [HttpGet("{id}")]
        public ActionResult<ValueCheck> GetById(int id)
        {
            return new ValueCheck{ Name = $"Value{id}", Value = id };
        }

        // POST /values
        [HttpPost]
        public void Post([FromBody] string value)
        {
            // For more information on protecting this API from Cross Site Request Forgery (CSRF) attacks, see https://go.microsoft.com/fwlink/?LinkID=717803
        }

        // PUT /values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
            // For more information on protecting this API from Cross Site Request Forgery (CSRF) attacks, see https://go.microsoft.com/fwlink/?LinkID=717803
        }

        // DELETE /values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
            // For more information on protecting this API from Cross Site Request Forgery (CSRF) attacks, see https://go.microsoft.com/fwlink/?LinkID=717803
        }
    }
}
```

**Comment by jaredcnance** [comment]
So, I'm not sure what you're trying to do. If you want this to be a JSON:API controller, try removing all of the methods (`JsonApiController` defines the default ones for you). You can also override any of the base methods if you need to add/change some behavior. You can also inherit from `BaseJsonApiController` instead.

Take a look at these two classes:

- [JsonApiController](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/c633c71aab7fcef023bb20aba5d41c420ad8a3cb/src/JsonApiDotNetCore/Controllers/JsonApiController.cs#L39)
- [BaseJsonApiController](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/c633c71aab7fcef023bb20aba5d41c420ad8a3cb/src/JsonApiDotNetCore/Controllers/BaseJsonApiController.cs#L39)

**Comment by Dillie-O** [comment]
Greetings @jaredcnance 

My goal is to "JSON APIify" my new WebAPI so that all of my controller endpoints return their data "wrapped" in the JSON API standards, as well as include pagination details (other items I found elsewhere in the documentation) to better standardize my new project.

According to the step by step guide, the "Person" object (in my case ValueCheck) inherited from the "Identifiable" class and use data annotations for what the names should be. I did that to my ValueCheck object as well. I have no DB at this point. I'm literally at "step 1" in getting this scaffold for my team and want to make sure the "happy path" items work before I get into database queries and the like.

However, looking over things some more, are you saying that the default JsonAPIController is setting up its own default routing to the GET/POST/PUT/DELETE verbs and I only need to override them as necessary, or create additional actions?
