### ISSUE TITLE
Issue on findAll

### ISSUE THREAD

**Issue by woofi7** [json-api-dotnet/JsonApiDotNetCore#729]
## Description

Recently I've started to encounter multiples errors while fetching data from the api. After searching for the problem I didn't find anything about it in the configuration the deffinition of the models. My project is pretty simple with a couple of models and the I'm only using the basic fonctions from jsonapi. The get.

Here is the error generated by the server:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at JsonApiDotNetCore.Query.FilterService..ctor(IResourceDefinitionProvider resourceDefinitionProvider, IResourceGraph resourceGraph, ICurrentRequest currentRequest)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at JsonApiDotNetCore.Builders.JsonApiApplicationBuilder.<>c.<AddQueryParameterServices>b__12_1(IServiceProvider sp)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Mvc.ServiceFilterAttribute.CreateInstance(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
   at Microsoft.AspNetCore.Mvc.Filters.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.CreateUncachedFiltersCore(IFilterProvider[] filterProviders, ActionContext actionContext, List 1 filterItems)
   at Microsoft.AspNetCore.Mvc.Filters.FilterFactory.CreateUncachedFilters(IFilterProvider[] filterProviders, ActionContext actionContext, FilterItem[] cachedFilterItems)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at JsonApiDotNetCore.Middleware.CurrentRequestMiddleware.Invoke(HttpContext httpContext, IControllerResourceMapping controllerResourceMapping, IJsonApiOptions options, ICurrentRequest currentRequest, IResourceGraph resourceGraph)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

The Startup.cs config, very simple:
`   public void ConfigureServices(IServiceCollection services)
   {
      services.AddSwaggerGen(c =>
      {
         c.SwaggerDoc("v1", new OpenApiInfo { Title = "L'Agenda API", Version = "v1" });
      });
      services.AddControllers();
      services.AddDbContext<AppDbContext>();
      services.AddSingleton<IResourceNameFormatter, KebabCaseFormatter>();
      services.AddJsonApi<AppDbContext>(options =>
      {
         options.Namespace = "api/v1";
         options.DefaultPageSize = 20;
         options.IncludeTotalRecordCount = true;
         options.LoadDatabaseValues = true;
         options.ValidateModelState = true;
         options.EnableResourceHooks = true;
      });
      services.AddCors();
   }

   // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
   public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
   {
     if (env.IsDevelopment())
      {
          app.UseDeveloperExceptionPage();

          app.UseSwagger();

          app.UseSwaggerUI(c =>
          {
             c.SwaggerEndpoint("/swagger/v1/swagger.json", "L'Agenda API v1");
             c.RoutePrefix = string.Empty;
          });
      }

      app.UseRouting();

      app.UseCors(a => a.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader());
      app.UseAuthorization();

      app.UseJsonApi();

      app.UseEndpoints(endpoints =>
      {
          endpoints.MapControllers();
      });
   }`

I'm getting the error while fetching relations data, the first call is http://localhost:5000/api/v1/articles/ which will trigger a couple of calls like this one http://localhost:5000/api/v1/articles/9/article-category . Ans the second call will generate the error.

## Environment

- JsonApiDotNetCore Version: 4.0.0-alpha4
- Other Relevant Package Versions: Dotnet Core v3.1

**Comment by YaLehin** [comment]
It seems to be the same as https://github.com/json-api-dotnet/JsonApiDotNetCore/issues/727

**Comment by bart-degreed** [comment]
Yes, this sounds like the bug I fixed this week. Can you try with the latest build of master?

**Comment by bart-degreed** [comment]
Closing as duplicate.
